- name: download and install tailscale
  shell: | 
    curl -fsSL https://tailscale.com/install.sh | sh
  args:
    executable: /bin/bash

- name: join to tailscale
  shell: |
    tailscale up --authkey {{ TAILSCALE_JOIN_KEY }} --accept-routes
  become: yes



